[project]
name = "rag-project"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Hector S Lazcano Quintero M", email = "hectorslqm@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "datasets>=5.0.1",
    "matplotlib>=3.11.1",
    "numpy>=2.5.2",
    "openai>=3.6.0",
    "pandas>=3.0.5",
    "python-dotenv>=1.2.3",
    "sentence-transformers>=6.0.0",
]

[project.scripts]
rag-project = "rag_project:main"

[build-system]
requires = ["uv_build>=0.12.7,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "ipykernel>=7.3.0",
    "jupytext>=1.19.5",
    "pandas-stubs>=3.0.5.260730",
    "ruff>=0.16.5",
]
